name: 'Anvil-ZKsync Action'
description: 'GitHub Action that simplifies running `anvil-zksync` in your CI/CD workflows!'
author: 'Dustin Brickwood'
branding:
  icon: 'check-circle'
  color: 'green'
inputs:
  releaseTag:
    description: "Release tag of anvil-zksync to use (default: latest)"
    required: false
    default: "latest"
  target:
    description: "Target architecture (default: x86_64-unknown-linux-gnu)"
    required: false
    default: "x86_64-unknown-linux-gnu"
  mode:
    description: "Mode to run the node (run or fork)"
    required: false
    default: "run"
  forkUrl:
    description: "Network to fork from (e.g., http://XXX:YY, mainnet, sepolia-testnet)"
    required: false
  forkBlockNumber:
    description: "Fetch state from a specific block number over a remote endpoint"
    required: false
  forkTransactionHash:
    description: "Fetch state from a specific transaction hash over a remote endpoint"
    required: false
  port:
    description: "Port to listen on (default: 8011)"
    required: false
    default: "8011"
  host:
    description: "The host IP address to listen on (default: 127.0.0.1)"
    required: false
    default: "127.0.0.1"
  chainId:
    description: "Specify chain ID (default: 260)"
    required: false
    default: "260"
  showStorageLogs:
    description: "Show storage log information (none, read, write, paid, all)"
    required: false
  showVmDetails:
    description: "Show VM details information (none, all)"
    required: false
  showGasDetails:
    description: "Show gas details information (none, all)"
    required: false
  log:
    description: "Log level (trace, debug, info, warn, error)"
    required: false
    default: "info"
  logFilePath:
    description: "Log file path (default: anvil_zksync.log)"
    required: false
    default: "anvil_zksync.log"
  offline:
    description: "Run in offline mode (true, false)"
    required: false
    default: "false"
  healthCheckEndpoint:
    description: "Enable health check endpoint (true, false)"
    required: false
    default: "false"
  configOut:
    description: "Output config file path"
    required: false
  l1GasPrice:
    description: "Custom L1 gas price"
    required: false
  l2GasPrice:
    description: "Custom L2 gas price"
    required: false
  l1PubdataPrice:
    description: "Custom L1 pubdata price"
    required: false
  priceScaleFactor:
    description: "Gas price estimation scale factor"
    required: false
  limitScaleFactor:
    description: "Gas limit estimation scale factor"
    required: false
  overrideBytecodesDir:
    description: "Directory to override bytecodes"
    required: false
  devSystemContracts:
    description: "Option for system contracts (built-in, local, built-in-without-security)"
    required: false
  emulateEvm:
    description: "Enable EVM emulation (true, false)"
    required: false
    default: "false"
  cache:
    description: "Cache type (none, memory, disk)"
    required: false
    default: "disk"
  resetCache:
    description: "Reset the local disk cache (true, false)"
    required: false
    default: "false"
  cacheDir:
    description: "Cache directory location for disk cache (default: .cache)"
    required: false
    default: ".cache"
  accounts:
    description: "Number of dev accounts to generate and configure (default: 10)"
    required: false
    default: "10"
  balance:
    description: "The balance of every dev account in Ether (default: 10000)"
    required: false
    default: "10000"
  mnemonic:
    description: "BIP39 mnemonic phrase for generating accounts"
    required: false
  mnemonicRandom:
    description: "Automatically generate a BIP39 mnemonic phrase (number of words, default: 12)"
    required: false
  mnemonicSeedUnsafe:
    description: "Generate a BIP39 mnemonic from a given seed (unsafe for production)"
    required: false
  derivationPath:
    description: "Derivation path of the child key to be derived (default: m/44'/60'/0'/0/)"
    required: false
    default: "m/44'/60'/0'/0/"
  autoImpersonate:
    description: "Enable automatic impersonation on startup (true, false)"
    required: false
    default: "false"
  blockTime:
    description: "Block time in seconds for interval sealing"
    required: false
  protocolVersion:
    description: "Protocol to use (e.g. 27)"
    required: false
  enforceBytecodeCompression:
    description: "Enforce bytecode compression on system contracts"
    required: false
    default: "false"
  systemContractsPath:
    description: "Override path to compiled system contracts"
    required: false
  showNodeConfig:
    description: "Print node config at startup"
    required: false
    default: "false"
  verbosity:
    description: "Verbosity level (-v, -vv, …)"
    required: false
    default: "0"
  timestamp:
    description: "Genesis block timestamp"
    required: false
  init:
    description: "Path to genesis.json"
    required: false
  state:
    description: "Path for combined load/dump state file"
    required: false
  stateInterval:
    description: "Interval (sec) to dump state"
    required: false
  dumpState:
    description: "Path to dump chain state on exit"
    required: false
  preserveHistoricalStates:
    description: "Keep historical snapshots when dumping state"
    required: false
    default: "false"
  loadState:
    description: "Path to load saved state snapshot"
    required: false
  noMining:
    description: "Disable auto-mining (mine on demand)"
    required: false
    default: "false"
  allowOrigin:
    description: "CORS allow-origin header"
    required: false
    default: "*"
  noCors:
    description: "Disable CORS entirely"
    required: false
    default: "false"
  order:
    description: "Transaction ordering (fifo, …)"
    required: false
    default: "fifo"
  spawnL1:
    description: "Port to spawn L1 anvil if enabling L1"
    required: false
  externalL1:
    description: "External L1 JSON-RPC endpoint"
    required: false
  autoExecuteL1:
    description: "Auto execute L1 batches (requires L1 enabled)"
    required: false
    default: "false"
  baseTokenSymbol:
    description: "Base token symbol (defaults to ETH)"
    required: false
  baseTokenRatio:
    description: "Base token conversion ratio"
    required: false
  extra-args:
    description: "Raw extra args for advanced use"
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
